receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
        cors:
          allowed_origins: [http://localhost:5173]
          # allowed_headers: []
          max_age: 3600

processors:
  batch:

exporters:
  # Debug Exporter: Prints telemetry directly to the container logs
  debug:
    verbosity: basic # Options: silent, basic, normal, detailed

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/zipkinexporter/README.md
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: json
    default_service_name: unknown-service

  # Prometheus Exporter: Exposes metrics for Prometheus to scrape
  prometheus:
    endpoint: "0.0.0.0:8889" # This maps to the 'otel-collector-pipeline' target

  # elasticsearch:
  #   # URL pointing to the static IP/hostname of the Elasticsearch service block
  #   endpoint: "http://elasticsearch:9200"
  #   # Basic Authentication using the cluster superuser account
  #   user: elastic
  #   password: elastic
  #   # Mode mapping ensures OTel metrics comply with Elastic Common Schema indices
  #   mapping:
  #     mode: otel

  # splunk_hec:
  #   endpoint: "https://splunk:8088"
  #   # Replace with your generated Splunk HEC Token
  #   token: 11111111-1111-1111-1111-111111111111
  #   # Target index inside Splunk (Must be configured as a 'Metrics' type index)
  #   index: "metrics"
  #   # Overrides the default source type for OpenTelemetry metrics tracking
  #   sourcetype: "otel"
  #   # Set to true if you are using self-signed SSL certificates on your Splunk instance
  #   tls:
  #     insecure_skip_verify: true

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus] # Activates the exporters defined above
