export type ShapeDefinition = {
	name: string
	id: string
}

export const shapes: ShapeDefinition[] = [
	{ name: "Square", id: "square" },
	{ name: "Rectangle", id: "rectangle" },
	{ name: "Circle", id: "circle" },
	{ name: "Oval", id: "oval" },
	{ name: "TriangleUp", id: "triangle-up" },
	{ name: "TriangleDown", id: "triangle-down" },
	{ name: "TriangleLeft", id: "triangle-left" },
	{ name: "TriangleRight", id: "triangle-right" },
	{ name: "TriangleTopLeft", id: "triangle-top-left" },
	{ name: "TriangleTopRight", id: "triangle-top-right" },
	{ name: "TriangleBottomLeft", id: "triangle-bottom-left" },
	{ name: "TriangleBottomRight", id: "triangle-bottom-right" },
	{ name: "CurvedArrow", id: "curved-arrow" },
	{ name: "Trapezoid", id: "trapezoid" },
	{ name: "Parallelogram", id: "parallelogram" },
	{ name: "StarSix", id: "star-six" },
	{ name: "StarFive", id: "star-five" },
	{ name: "Pentagon", id: "pentagon" },
	{ name: "Hexagon", id: "hexagon" },
	{ name: "Octagon", id: "octagon" },
	{ name: "Heart", id: "heart" },
	{ name: "InfinityShape", id: "infinity" },
	{ name: "Diamond", id: "diamond" },
	{ name: "DiamondShield", id: "diamond-shield" },
	{ name: "DiamondNarrow", id: "diamond-narrow" },
	{ name: "CutDiamond", id: "cut-diamond" },
	{ name: "Egg", id: "egg" },
	{ name: "Pacman", id: "pacman" },
	{ name: "TalkBubble", id: "talk-bubble" },
	{ name: "Rss", id: "rss" },
	{ name: "Burst12", id: "burst-12" },
	{ name: "Burst8", id: "burst-8" },
	{ name: "YinYang", id: "yin-yang" },
	{ name: "BadgeRibbon", id: "badge-ribbon" },
	{ name: "SpaceInvader", id: "space-invader" },
	{ name: "Tv", id: "tv" },
	{ name: "Chevron", id: "chevron" },
	{ name: "MagnifyingGlass", id: "magnifying-glass" },
	{ name: "FacebookIcon", id: "facebook-icon" },
	{ name: "Moon", id: "moon" },
	{ name: "Flag", id: "flag" },
	{ name: "Cone", id: "cone" },
	{ name: "Cross", id: "cross" },
	{ name: "Base", id: "base" },
	{ name: "Pointer", id: "pointer" },
	{ name: "Lock", id: "lock" },
	{ name: "CurvedCornerBottomLeft", id: "curved-corner-bottom-left" },
	{ name: "CurvedCornerBottomRight", id: "curved-corner-bottom-right" },
	{ name: "CurvedCornerTopLeft", id: "curved-corner-top-left" },
	{ name: "CurvedCornerTopRight", id: "curved-corner-top-right" },
]
