name: Build experimental-ui-on-microfw-webpack
on:
  pull_request:
    paths:
      - .github/workflows/build-experimental-ui-on-microfw-webpack.yaml
      - experimental-ui-on-microfw-webpack/**
    types:
      - opened
      - reopened
      - synchronize

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Node.js
        # https://github.com/marketplace/actions/setup-node-js-environment
        uses: actions/setup-node@v6
        with:
          node-version-file: experimental-ui-on-microfw-webpack/package.json
        
      - name: Install dependencies
        shell: bash
        working-directory: experimental-ui-on-microfw-webpack
        run: npm ci

      - name: Check code formatting
        id: check_format
        continue-on-error: true
        shell: bash
        working-directory: experimental-ui-on-microfw-webpack
        run: npm run check-format

      - name: Show format logs on check failure
        if: steps.check_format.outcome == 'failure'
        shell: bash
        working-directory: experimental-ui-on-microfw-webpack
        run: |
          npm run format
          exit 1

      - name: Run ESLint
        shell: bash
        working-directory: experimental-ui-on-microfw-webpack
        run: npm run lint

      - name: Run tests
        shell: bash
        working-directory: experimental-ui-on-microfw-webpack
        run: npm run test

      - name: Build experimental-ui-on-microfw-webpack
        shell: bash
        working-directory: experimental-ui-on-microfw-webpack
        run: npm run build
