name: Build experimental-ui-on-electron
on:
  pull_request:
    paths:
      - .github/workflows/build-experimental-ui-on-electron.yaml
      - experimental-ui-on-electron/**
    types:
      - opened
      - reopened
      - synchronize

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Node.js
        # https://github.com/marketplace/actions/setup-node-js-environment
        uses: actions/setup-node@v6
        with:
          node-version-file: experimental-ui-on-electron/package.json
        
      - name: Install dependencies
        shell: bash
        working-directory: experimental-ui-on-electron
        run: npm ci

      - name: Check code formatting
        id: check_format
        continue-on-error: true
        shell: bash
        working-directory: experimental-ui-on-electron
        run: npm run check-format

      - name: Show format logs on check failure
        if: steps.check_format.outcome == 'failure'
        shell: bash
        working-directory: experimental-ui-on-electron
        run: |
          npm run format
          exit 1

      - name: Run ESLint
        shell: bash
        working-directory: experimental-ui-on-electron
        run: npm run lint

      - name: Run unit tests
        shell: bash
        working-directory: experimental-ui-on-electron
        run: npm run test:unit

      - name: Install XVFB and dependencies for Electron
        shell: bash
        working-directory: experimental-ui-on-electron
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libgtk-3-0 \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libgbm1 \
            libxkbcommon0 \
            libxshmfence1

      - name: Run tests with virtual display
        shell: bash
        working-directory: experimental-ui-on-electron
        run: xvfb-run --auto-servernum npm run test:e2e

      - name: Build experimental-ui-on-electron
        shell: bash
        working-directory: experimental-ui-on-electron
        run: npm run make
