name: Build experimental-css-on-vue
on:
  pull_request:
    paths:
      - .github/workflows/build-experimental-css-on-vue.yaml
      - experimental-css-on-vue/**
    types:
      - opened
      - reopened
      - synchronize

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Node.js
        # https://github.com/marketplace/actions/setup-node-js-environment
        uses: actions/setup-node@v6
        with:
          node-version-file: experimental-css-on-vue/package.json
 
      - name: Install dependencies
        shell: bash
        working-directory: experimental-css-on-vue
        run: npm ci

      - name: Check code formatting
        id: check_format
        continue-on-error: true
        shell: bash
        working-directory: experimental-css-on-vue
        run: npm run check-format

      - name: Show format logs on check failure
        if: steps.check_format.outcome == 'failure'
        shell: bash
        working-directory: experimental-css-on-vue
        run: |
          npm run format
          exit 1

      - name: Run checks
        shell: bash
        working-directory: experimental-css-on-vue
        run: |
          npm run lint
          npm run type-check

      - name: Run unit tests
        shell: bash
        working-directory: experimental-css-on-vue
        run: npm run test:unit

      # - name: Run E2E tests
      #   shell: bash
      #   working-directory: experimental-css-on-vue
      #   run: |
      #     npm run prepare
      #     npm run test:e2e

      - name: Build experimental-css-on-vue
        shell: bash
        working-directory: experimental-css-on-vue
        run: npm run build
